services:
  api:
    build: .
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "${API_PORT}:8000"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
