services:  
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
        - "1080:8025"
    networks:
        - php     
  php:
    image: scheffer_shen/php72:latest
    #build: ./docker/php
    container_name: php
    user: '1000:1000'
    working_dir: /var/www/html
    volumes:
      - "./:/var/www/html"
    networks:
      - mysql
      - php    
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --max_allowed_packet=32505856 
    environment:
      MYSQL_ROOT_PASSWORD: 9TT4fgq5
      MYSQL_DATABASE: keycloak
    ports:
      - 3306:3306      
    working_dir: /home  
    volumes:
      - "./docker/.data/db:/var/lib/mysql"
      - "./sql:/home"
    networks:
      - mysql    
  caddy:
    image: caddy:2.8.4
    container_name: caddy
    environment:
      SERVER_NAME: ${SERVER_NAME:-lms3.universalmedica.local, caddy:80}
    ports:
      - 80:80
      - 443:443
    working_dir: /var/www/html
    volumes:
      - "./public:/var/www/html/public"    
      - "./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./docker/.data/caddy/data:/data"
      - "./docker/.data/caddy/config:/config"  
    networks:
      - php
  keycloak:
      image: bitnami/keycloak:15.0.2-debian-10-r66 #jboss/keycloak:15.0.2 #https://gist.github.com/htuscher/b446a779321ffb3c572104695e9f02fb
      container_name: keycloak
      ports:
          - "8443:8443"
      environment:
          DB_VENDOR: mysql
          DB_ADDR: mysql
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: 9TT4fgq5
          DB_DATABASE: keycloak
          KEYCLOAK_USER: root
          KEYCLOAK_PASSWORD: root
          KEYCLOAK_IMPORT: '/opt/jboss/keycloak/examples-realm.json'
      networks:
          - mysql
      depends_on:
          - mysql
      volumes:
          - ./realm-export.json:/opt/jboss/keycloak/examples-realm.json
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always    
    ports:
      - "8080:80"      
    environment:
        PMA_HOST: mysql
    networks:
      - mysql   
  fastapi:
    image: scheffer_shen/fastapi
    #build:
    #  context: ./bonus/api
    #  dockerfile: Dockerfile
    container_name: fastapi
    volumes:
      - ./bonus/api:/app/bonus/api
    ports:
      - "${API_PORT:-8000}:8000"  
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    #ports: [6379]
    networks:
      - php 
  mcp-mysql:
    image: mineru/mcp-mysql:1.0.0
    container_name: mcp-mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=9TT4fgq5
      - MYSQL_DATABASE=lms_test
      - MCP_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - mysql  
    depends_on:
      mysql:
        condition: service_healthy

networks:
    php:
        driver: bridge
    mysql:
        driver: bridge      
